import {
  FileEdit,
  Files,
  Split,
  Layers,
  FileText,
  FileCheck,
  ScanText,
  Minimize2,
  Stamp,
  Hash,
  Images,
  Image as ImageIcon,
  Sparkles,
  QrCode,
  Sliders,
  Pen,
  RotateCw,
  Trash2,
  FolderOutput,
  Lock,
  Unlock,
  ShieldAlert,
  FormInput,
} from 'lucide-react';
import type { ToolDefinition, ToolCategory } from '../types/tools';

export const TOOL_CATEGORIES: { id: ToolCategory; label: string; description: string }[] = [
  { id: 'pdf', label: 'PDF Essentials', description: 'Merge, split, compress, organize, and extract PDF pages.' },
  { id: 'edit', label: 'Edit & Sign', description: 'Annotate, add signatures, redact, protect, and fill forms.' },
  { id: 'convert', label: 'Conversion', description: 'High-fidelity conversion between PDF, Word, and JPG.' },
  { id: 'ocr', label: 'OCR & Text', description: 'Extract editable text from scanned documents and images.' },
  { id: 'image', label: 'Image Tools', description: 'Convert, compress, and package images to/from PDF.' },
  { id: 'productivity', label: 'Productivity', description: 'Text cleanup, diff tools, QR code generator and utilities.' },
];

export const ALL_TOOLS: ToolDefinition[] = [
  {
    id: 'pdf-editor',
    name: 'PDF Editor',
    category: 'edit',
    description: 'Edit PDF text directly, add text overlays, draw, place signatures, stamps, and shapes.',
    iconName: 'FileEdit',
    icon: FileEdit,
    badge: 'Core',
    route: '/pdf-editor',
    keywords: ['editor', 'edit', 'annotate', 'signature', 'sign', 'draw', 'stamp', 'text', 'redact', 'notes'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 1,
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    category: 'convert',
    description: 'Convert PDF files into editable Microsoft Word (.docx) documents with layout fidelity.',
    iconName: 'FileText',
    icon: FileText,
    badge: 'Popular',
    route: '/pdf-to-word',
    keywords: ['pdf to word', 'docx', 'doc', 'convert', 'extract', 'editable word', 'microsoft word'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.docx',
    outputMimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    priority: 2,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    category: 'convert',
    description: 'Convert Microsoft Word (.docx) files into standard, high-fidelity PDF documents.',
    iconName: 'FileCheck',
    icon: FileCheck,
    badge: 'Popular',
    route: '/word-to-pdf',
    keywords: ['word to pdf', 'docx to pdf', 'doc to pdf', 'convert docx', 'save as pdf'],
    acceptedInputMimeTypes: [
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/msword',
    ],
    acceptedInputExtensions: ['.docx', '.doc'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 3,
  },
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    category: 'pdf',
    description: 'Combine multiple PDF files into a single unified document in any chosen order.',
    iconName: 'Files',
    icon: Files,
    badge: 'Core',
    route: '/merge-pdf',
    keywords: ['merge', 'combine', 'join', 'append', 'concatenate', 'group pdf'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 4,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    category: 'pdf',
    description: 'Split a PDF into individual pages or extract custom page ranges into new documents.',
    iconName: 'Split',
    icon: Split,
    badge: 'Core',
    route: '/split-pdf',
    keywords: ['split', 'separate', 'extract pages', 'divide', 'slice pdf', 'break pdf'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 5,
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    category: 'edit',
    description: 'Sign PDF contracts with drawn signatures, cursive typography, date stamps, and image uploads.',
    iconName: 'Pen',
    icon: Pen,
    badge: 'Popular',
    route: '/sign-pdf',
    keywords: ['sign pdf', 'signature', 'sign', 'electronic signature', 'esign', 'initials', 'contracts'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 6,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    category: 'pdf',
    description: 'Rotate PDF pages permanently 90, 180, or 270 degrees clockwise or counterclockwise.',
    iconName: 'RotateCw',
    icon: RotateCw,
    badge: 'Core',
    route: '/rotate-pdf',
    keywords: ['rotate pdf', 'turn pages', 'orientation', 'flip', 'upside down', 'landscape', 'portrait'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 7,
  },
  {
    id: 'delete-pdf-pages',
    name: 'Delete Pages',
    category: 'pdf',
    description: 'Remove unwanted pages, odd or even sets, or custom ranges from your PDF document.',
    iconName: 'Trash2',
    icon: Trash2,
    badge: 'Core',
    route: '/delete-pdf-pages',
    keywords: ['delete pages', 'remove page', 'cut pages', 'drop pages', 'delete sheets'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 8,
  },
  {
    id: 'extract-pdf-pages',
    name: 'Extract Pages',
    category: 'pdf',
    description: 'Extract selected pages into a standalone PDF or export all pages as individual files.',
    iconName: 'FolderOutput',
    icon: FolderOutput,
    badge: 'Popular',
    route: '/extract-pdf-pages',
    keywords: ['extract pages', 'save pages', 'isolate page', 'rip pdf', 'export pages'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 9,
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    category: 'edit',
    description: 'Encrypt PDF files with client-side AES-256 passwords and granular permissions.',
    iconName: 'Lock',
    icon: Lock,
    badge: 'Popular',
    route: '/protect-pdf',
    keywords: ['protect pdf', 'encrypt pdf', 'password protect', 'lock pdf', 'secure pdf', 'aes-256'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 10,
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    category: 'edit',
    description: 'Remove password restrictions and decrypt protected PDFs directly on your device.',
    iconName: 'Unlock',
    icon: Unlock,
    badge: 'Utility',
    route: '/unlock-pdf',
    keywords: ['unlock pdf', 'remove password', 'decrypt pdf', 'unprotect', 'clear password'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 11,
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    category: 'edit',
    description: 'Permanently remove and scrub confidential text, SSNs, and sensitive data from PDF files.',
    iconName: 'ShieldAlert',
    icon: ShieldAlert,
    badge: 'Popular',
    route: '/redact-pdf',
    keywords: ['redact pdf', 'blackout', 'sanitize', 'remove sensitive info', 'hide text', 'confidential'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 12,
  },
  {
    id: 'fill-pdf',
    name: 'Fill PDF Forms',
    category: 'edit',
    description: 'Fill out interactive AcroForm fields, text boxes, checkboxes, and radio buttons with auto-flattening.',
    iconName: 'FormInput',
    icon: FormInput,
    badge: 'New',
    route: '/fill-pdf',
    keywords: ['fill pdf', 'form filler', 'acroforms', 'pdf fields', 'fill out tax form', 'fillable pdf'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 13,
  },
  {
    id: 'organize-pdf',
    name: 'Organize PDF',
    category: 'pdf',
    description: 'Reorder pages visually, duplicate pages, or delete unneeded pages in a visual drag-and-drop grid.',
    iconName: 'Layers',
    icon: Layers,
    badge: 'Core',
    route: '/organize-pdf',
    keywords: ['organize', 'reorder', 'rotate', 'delete pages', 'duplicate', 'rearrange', 'orient'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 14,
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    category: 'pdf',
    description: 'Optimize PDF file size while maintaining visual legibility and vector clarity.',
    iconName: 'Minimize2',
    icon: Minimize2,
    badge: 'Popular',
    route: '/compress-pdf',
    keywords: ['compress', 'reduce size', 'optimize', 'shrink', 'smaller pdf', 'lighten'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 15,
  },
  {
    id: 'ocr-pdf',
    name: 'OCR & Extract Text',
    category: 'ocr',
    description: 'Extract text from scanned PDFs and images locally in browser with Tesseract OCR.',
    iconName: 'ScanText',
    icon: ScanText,
    badge: 'Popular',
    route: '/ocr-pdf',
    keywords: ['ocr', 'text recognition', 'scanned pdf', 'tesseract', 'extract text', 'searchable pdf'],
    acceptedInputMimeTypes: ['application/pdf', 'image/png', 'image/jpeg', 'image/webp'],
    acceptedInputExtensions: ['.pdf', '.png', '.jpg', '.jpeg', '.webp'],
    outputExtension: '.txt',
    outputMimeType: 'text/plain',
    priority: 16,
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    category: 'convert',
    description: 'Convert PDF pages into high-resolution JPG images with selectable DPI and ZIP download.',
    iconName: 'ImageIcon',
    icon: ImageIcon,
    badge: 'Popular',
    route: '/pdf-to-jpg',
    keywords: ['pdf to jpg', 'pdf to jpeg', 'extract jpg', 'export pdf as pictures', 'jpg photos'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.jpg',
    outputMimeType: 'image/jpeg',
    priority: 17,
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    category: 'convert',
    description: 'Merge and convert multiple JPG photos into a single clean PDF document.',
    iconName: 'Images',
    icon: Images,
    badge: 'Popular',
    route: '/jpg-to-pdf',
    keywords: ['jpg to pdf', 'jpeg to pdf', 'images to pdf', 'photos to pdf', 'picture to document'],
    acceptedInputMimeTypes: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
    acceptedInputExtensions: ['.jpg', '.jpeg', '.png', '.webp'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 18,
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    category: 'convert',
    description: 'Render PDF pages into lossless high-definition PNG images with transparent background support.',
    iconName: 'ImageIcon',
    icon: ImageIcon,
    badge: 'Popular',
    route: '/pdf-to-png',
    keywords: ['pdf to png', 'extract png', 'export pdf as png', 'transparent png', 'lossless'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.png',
    outputMimeType: 'image/png',
    priority: 18.5,
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    category: 'convert',
    description: 'Convert and merge transparent or high-res PNG images into a clean, unified PDF.',
    iconName: 'Images',
    icon: Images,
    badge: 'Popular',
    route: '/png-to-pdf',
    keywords: ['png to pdf', 'images to pdf', 'photos to pdf', 'combine png', 'batch png'],
    acceptedInputMimeTypes: ['image/png'],
    acceptedInputExtensions: ['.png'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 18.6,
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    category: 'edit',
    description: 'Apply text or image watermarks with customized opacity, rotation angle, and placement.',
    iconName: 'Stamp',
    icon: Stamp,
    badge: 'Utility',
    route: '/watermark-pdf',
    keywords: ['watermark', 'stamp', 'confidential', 'draft', 'brand', 'copyright'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 19,
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    category: 'edit',
    description: 'Add customizable page numbers and running headers/footers across your document.',
    iconName: 'Hash',
    icon: Hash,
    badge: 'Utility',
    route: '/page-numbers',
    keywords: ['page numbers', 'paginate', 'header', 'footer', 'numbering', 'bates'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 20,
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    category: 'image',
    description: 'Render PDF pages into high-resolution PNG or JPEG images with selectable DPI.',
    iconName: 'ImageIcon',
    icon: ImageIcon,
    badge: 'Utility',
    route: '/pdf-to-images',
    keywords: ['pdf to image', 'pdf to png', 'pdf to jpg', 'export pages', 'render pdf'],
    acceptedInputMimeTypes: ['application/pdf'],
    acceptedInputExtensions: ['.pdf'],
    outputExtension: '.png',
    outputMimeType: 'image/png',
    priority: 21,
  },
  {
    id: 'images-to-pdf',
    name: 'Images to PDF',
    category: 'image',
    description: 'Convert PNG, JPG, and WebP images into a single clean PDF with custom page geometry.',
    iconName: 'Images',
    icon: Images,
    badge: 'Utility',
    route: '/images-to-pdf',
    keywords: ['images to pdf', 'jpg to pdf', 'png to pdf', 'photos to pdf', 'convert image'],
    acceptedInputMimeTypes: ['image/png', 'image/jpeg', 'image/webp'],
    acceptedInputExtensions: ['.png', '.jpg', '.jpeg', '.webp'],
    outputExtension: '.pdf',
    outputMimeType: 'application/pdf',
    priority: 22,
  },
  {
    id: 'image-optimizer',
    name: 'Image Studio',
    category: 'image',
    description: 'Resize dimensions, convert formats, and optimize image files directly in the browser.',
    iconName: 'Sliders',
    icon: Sliders,
    badge: 'Utility',
    route: '/image-optimizer',
    keywords: ['image resize', 'compress image', 'convert image', 'crop', 'png to webp'],
    acceptedInputMimeTypes: ['image/png', 'image/jpeg', 'image/webp'],
    acceptedInputExtensions: ['.png', '.jpg', '.jpeg', '.webp'],
    outputExtension: '.webp',
    outputMimeType: 'image/webp',
    priority: 23,
  },
  {
    id: 'text-tools',
    name: 'Text Utilities',
    category: 'productivity',
    description: 'Case converter, whitespace cleanup, duplicate line remover, stats, and text diff.',
    iconName: 'Sparkles',
    icon: Sparkles,
    badge: 'Utility',
    route: '/text-tools',
    keywords: ['text tools', 'diff', 'case convert', 'count words', 'clean text', 'dedupe lines'],
    acceptedInputMimeTypes: ['text/plain'],
    acceptedInputExtensions: ['.txt', '.md'],
    outputExtension: '.txt',
    outputMimeType: 'text/plain',
    priority: 24,
  },
  {
    id: 'qr-studio',
    name: 'QR Studio',
    category: 'productivity',
    description: 'Generate high-resolution QR codes and scan QR codes from uploaded images locally.',
    iconName: 'QrCode',
    icon: QrCode,
    badge: 'Utility',
    route: '/qr-studio',
    keywords: ['qr code', 'barcode', 'generate qr', 'scan qr', 'wifi qr', 'url qr'],
    acceptedInputMimeTypes: ['image/png', 'image/jpeg', 'image/webp'],
    acceptedInputExtensions: ['.png', '.jpg', '.jpeg', '.webp'],
    outputExtension: '.png',
    outputMimeType: 'image/png',
    priority: 25,
  },
];

export function findToolById(id: string): ToolDefinition | undefined {
  return ALL_TOOLS.find((t) => t.id === id);
}

export function searchTools(query: string): ToolDefinition[] {
  const clean = query.trim().toLowerCase();
  if (!clean) return ALL_TOOLS;

  return ALL_TOOLS.filter((tool) => {
    return (
      tool.name.toLowerCase().includes(clean) ||
      tool.description.toLowerCase().includes(clean) ||
      tool.keywords.some((kw) => kw.includes(clean)) ||
      tool.category.toLowerCase().includes(clean)
    );
  }).sort((a, b) => a.priority - b.priority);
}
